import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '../src/services/auth'; // Import AuthProvider
import { ErrorProvider } from '../src/services/error'; // Import ErrorProvider
import ErrorDisplay from '../src/components/ErrorDisplay'; // Import ErrorDisplay

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ErrorProvider>
          <AuthProvider>
            <ErrorDisplay />
            {children}
          </AuthProvider>
        </ErrorProvider>
      </body>
    </html>
  );
}
